name: CI

on:
  - push
  - pull_request

jobs:
  npm-install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.1
          cache: npm

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

  prettier:
    name: Check prettier
    needs: npm-install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.1
          cache: npm

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Check files with prettier
        run: npm run prettier:check

  sync-kubit-docs-app-repo:
    name: Sync Kubit Docs app with this repo
    needs: prettier
    if: >-
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main' && 
      !contains(github.event.head_commit.message, '[SKIP SYNC DOCS APP]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jq
        uses: dcarbone/install-jq-action@v2

      - name: Sync Kubit Docs app with this repo
        env:
          API_ENDPOINT: ${{vars.API_ENDPOINT}}
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          COMMIT_MSG: ${{github.event.head_commit.message}}
        run: |-
          PAYLOAD=$(cat <<JSON
          {
            "commitHash": "$GITHUB_SHA",
            "commitMessage": $(jq --null-input --arg input "$COMMIT_MSG" '$input'),
            "authorName": "GH Actions"
          }
          JSON
          )
          echo "$PAYLOAD"
          curl -L --fail-with-body \
          -X PUT \
          -H "Authorization: Bearer $BEARER_TOKEN" \
          -H 'Content-Type: application/json' \
          -d "$PAYLOAD" \
          -s -o /dev/null --write-out '%{http_code}' \
          $API_ENDPOINT/sync-kubit-docs-repo
